### ISSUE TITLE
Switch to open services

### ISSUE THREAD

**Issue by Matthias84** [siacs/ShareLocationPlugin#12] opened 2016-07-01 19:54 UTC
Hi, currently  the plugin relies on proprietary google map services. This makes it impossible to host it via the open source http://www.f-droid.org repo or to use it on a Fairphone.

So I like to suggest to use open location services instead (e.g. [Mozilla location services](https://location.services.mozilla.com)). I'm not familar with the Android architecture itself, maybe it's just required that users install [different provider](https://f-droid.org/repository/browse/?fdfilter=Mozilla&fdid=org.microg.nlp.backend.ichnaea) ?

**Comment by SamWhited** [comment] 2016-07-01 19:56
Duplicate of #9 and #5

**Comment by iNPUTmice** [comment] 2016-07-01 19:56
Google for open share location plugin. It's hosted on bitbucket.

**Closed** 2016-07-01 20:52 UTC
